FROM ruby:2.3

RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update -qq && \
    apt-get install -y --allow-unauthenticated \
    build-essential \
    libsqlite3-dev \
    nodejs

WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock* /myapp/

RUN bundle install

COPY . /myapp

EXPOSE 3000
